#!/bin/sh

FILE=$1;

RED='\033[1;31m';
YELLOW='\033[1;33m';
NC='\033[0m';

VERSIONS='php55 php56 php7';

for version in $VERSIONS
do
    echo "============== ${YELLOW}${version}${NC}  ===============";

    output=`/usr/local/bin/${version} $FILE 2>&1`;
    if test $? != 0
    then
        output=${RED}${output}${NC};
    fi

    echo ${output}"\n";
done

